Repository emqx/emqx-management, pull requests merged in 2020-09, with the labels that each got.

#269 feature(clients): add ratelimit & quota policy API
  src/emqx_mgmt.erl
  src/emqx_mgmt_api_clients.erl
Labels: feature

#270 fix(pubsub api): cannot subscribe and unsubscribe via api in the cluster
  src/emqx_mgmt.erl
Labels: bug

#272 improve(api-clients): return the client's mountpoint
  src/emqx_mgmt.erl
Labels: enhancement

#274 fix(http): fix the ratelimit&quota http api
  src/emqx_mgmt_api_clients.erl
Labels: enhancement
