Repository emqx/emqx-management, pull requests merged in 2020-08, with the labels that each got.

#250 fix(publish api): Report an error when the payload is not in json format
  src/emqx_mgmt_api_pubsub.erl
  test/emqx_mgmt_api_SUITE.erl
Labels: bug

#251 fix(publish api): fix compile warning
  rebar.config
  src/emqx_mgmt_api_pubsub.erl
Labels: enhancement

#254 improve: eliminate compiling warngins on OTP 23
  src/emqx_mgmt_api_banned.erl
  src/emqx_mgmt_api_clients.erl
  src/emqx_mgmt_api_routes.erl
  src/emqx_mgmt_api_subscriptions.erl
  src/emqx_mgmt_api_topic_metrics.erl
  src/emqx_mgmt_util.erl
Labels: enhancement

#263 feature(sort-exported-file-list): sort file list according to create time
  src/emqx_mgmt_api_data.erl
Labels: feature

#261 fix(export-data-in-win): fix the issue that data cannot be exported due to path issues in windows
  src/emqx_mgmt_cli.erl
Labels: bug

#260 fix(api): convert anonymous funcs to M:F
  src/emqx_mgmt.erl
  src/emqx_mgmt_api.erl
  src/emqx_mgmt_api_clients.erl
  src/emqx_mgmt_api_subscriptions.erl
Labels: bug
